# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 12:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('фірмові_страви', 'фірмові_страви'), ('салат', 'салат'), ('холодні_закуски', 'холодні_закуски'), ('гарячі_закуски', 'гарячі_закуски'), ('перші_страви', 'перші_страви'), ('другі_страви', 'другі_страви'), ('гарніри', 'гарніри'), ('чай', 'чай'), ('кава', 'кава')], max_length=150), default=None, size=40)),
            ],
        ),
    ]
